### ISSUE TITLE
Error while running the app

### ISSUE THREAD

**Issue by gauravt** [JumpLink/magento-nodejs-sync-app#1]
Getting this error when i run the app : 

throw new Error('no port or path provided');
              ^
Error: no port or path provided

**Comment by JumpLink** [comment]
have you created a config file? This is required.
But you should wait, I want to rewrite this project.

**Comment by atul88** [comment]
# Hi , I am getting below error over terminal -  

atul@HO-GF-LAMP-63:~/magentonodesync/magento_nodejs$ node app.jsThere was an error opening the file:
{ [Error: ENOENT, no such file or directory '/home/atul/magentonodesync/magento_nodejs/config/general.json']
  errno: -2,
  code: 'ENOENT',
  path: '/home/atul/magentonodesync/magento_nodejs/config/general.json',
  syscall: 'open' }
/home/atul/magentonodesync/magento_nodejs/node_modules/express/lib/router/index.js:252
    throw new Error(msg);
          ^
Error: .get() requires callback functions but got a [object Undefined]
    at /home/atul/magentonodesync/magento_nodejs/node_modules/express/lib/router/index.js:252:11
    at Array.forEach (native)
    at Router.route (/home/atul/magentonodesync/magento_nodejs/node_modules/express/lib/router/index.js:248:13)
    at Router.(anonymous function) [as get](/home/atul/magentonodesync/magento_nodejs/node_modules/express/lib/router/index.js:270:16)
    at Function.app.(anonymous function) (/home/atul/magentonodesync/magento_nodejs/node_modules/express/lib/application.js:411:26)
    at Object.<anonymous> (/home/atul/magentonodesync/magento_nodejs/app.js:56:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

#     at Function.Module._load (module.js:310:12)

Can you plz help me to get out of this ? 

Thanks
